graphite:
   image: hopsoft/graphite-statsd
   ports:
      - "8000:80"
      - "2003:2003"
      - "2004:2004"
      - "2023:2023"
      - "2024:2024"
      - "8125:8125/udp"
      - "8126:8126"
grafana:
   image: grafana/grafana
   ports:
      - "3000:3000"
   links:
      - graphite
   environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
   volumes:
      - ./grafana/data:/var/lib/grafana



es-eureka:
   build: ./es-eureka
   ports:
      - "8761:8761"

es-gateway:
   build: ./es-gateway
   ports:
      - "80:8080"
   links:
      - es-eureka
      - es-slack

es-slack:
   build: ./es-slack
   ports:
      - "18502:18502"
   links:
      - es-eureka
      - graphite

